// The recipe book as Markdown.
//
// WHY MARKDOWN AT ALL. The owner asked for a file he keeps and I read: "once I
// input the information I want you to remember it and if I make any changes
// update the MD as well" (6 Oct 2026). The database is the live record; this is
// the copy that survives into a session months from now, when the reasoning
// behind a portion matters more than the number.
//
// WHERE IT CAN BE WRITTEN. Vercel's filesystem is read-only at runtime, so the
// app cannot commit docs/RECIPES.md itself. Two routes out, and they render the
// same text: /api/recipes/export downloads it on demand, and I regenerate the
// committed file from the database in a session.
//
// Pure: takes rows, returns a string.

import type { DishRecipe, VariantGroup, WorkRow } from './dish-recipes'

export type DocIngredient = { key: string; name: string; unit: string; counted: boolean }

const esc = (s: string) => String(s ?? '').replace(/\|/g, '\\|').trim()

const amount = (qty: number, unit: string) => {
  if (unit === 'g') return qty >= 1000 ? `${Math.round(qty / 10) / 100} kg` : `${qty} g`
  if (unit === 'fish') return `${qty} fish`
  return `${qty} pcs`
}

export function recipeDoc({
  rows, groups, ingredients, days, generated,
}: {
  rows: WorkRow[]
  groups: VariantGroup[]
  ingredients: DocIngredient[]
  days: number
  generated: string
}): string {
  const item = new Map(ingredients.map(i => [i.key, i]))
  const line = (l: { ingredient: string; qty: number }) => {
    const it = item.get(l.ingredient)
    return `${amount(l.qty, it?.unit ?? 'g')} ${it?.name ?? l.ingredient}${it && !it.counted ? ' *(not counted yet)*' : ''}`
  }
  const lines = (r: DishRecipe) =>
    r.lines.length ? r.lines.map(line).join(', ') : '*nothing we count*'

  const done = rows.filter(r => r.recipe)
  const todo = rows.filter(r => !r.recipe)
  const sold = rows.reduce((t, r) => t + r.sold, 0)
  const covered = done.reduce((t, r) => t + r.sold, 0)
  const pct = sold ? Math.round((covered / sold) * 100) : 0

  const out: string[] = []
  const p = (s = '') => out.push(s)

  p('# Jaosamut — the recipe book')
  p()
  p(`Generated ${generated} from CashflowOS. **Do not edit this file by hand** — it is`)
  p('rewritten from the database, so a change made here is lost. Change a recipe on')
  p('the Recipes page and this file follows.')
  p()
  p('Every entry is one POS dish plus the choices that change what it uses. Nothing')
  p('inherits from anything: a Medium is its own recipe, not a Small with a')
  p('multiplier (owner, 6 Oct 2026).')
  p()
  p(`**${done.length} of ${rows.length} written**, covering **${pct}%** of the ${sold.toLocaleString('en-MY')} dishes sold in the last ${days} days.`)
  p()

  // ── the choices ────────────────────────────────────────────────────────────
  p('## Which choices change a recipe')
  p()
  p('A choice marked *no* is stripped before a dish is matched, which is what stops')
  p('one dish becoming four recipes over sugar levels.')
  p()
  p('| Choice | Changes what’s used | Options |')
  p('|---|---|---|')
  for (const g of [...groups].sort((a, b) => a.label.localeCompare(b.label))) {
    const v = g.affects_stock === true ? 'yes' : g.affects_stock === false ? 'no' : '**not decided**'
    p(`| ${esc(g.label)} | ${v} | ${esc(g.options.join(', '))} |`)
  }
  p()

  // ── the dishes ─────────────────────────────────────────────────────────────
  const dishes = done.filter(r => r.kind === 'dish')
  p('## Dishes')
  p()
  p('| Dish | Choices | One serving uses | Sold | Sure? |')
  p('|---|---|---|---|---|')
  for (const r of dishes) {
    p(`| ${esc(r.dish_label)} | ${esc(r.variation_label) || '—'} | ${lines(r.recipe!)} | ${r.sold} | ${r.recipe!.sure ? 'yes' : '**no**'} |`)
  }
  if (!dishes.length) p('| *none written yet* | | | | |')
  p()

  // ── set parts ──────────────────────────────────────────────────────────────
  const parts = done.filter(r => r.kind === 'set_part')
  p('## Inside a set')
  p()
  p('A set line carries its choices, and each choice contributes its set portion.')
  p('This is the one place something is composed rather than written out in full:')
  p('91% of the sets sold were a combination never seen before (53 distinct out of')
  p('58, over 9 days), so writing every combination out would never finish.')
  p()
  p('| Choice | Set portion | Chosen | Sure? |')
  p('|---|---|---|---|')
  for (const r of parts) {
    p(`| ${esc(r.dish_label)} | ${lines(r.recipe!)} | ${r.sold} | ${r.recipe!.sure ? 'yes' : '**no**'} |`)
  }
  if (!parts.length) p('| *none written yet* | | | |')
  p()

  // ── notes ──────────────────────────────────────────────────────────────────
  const noted = done.filter(r => r.recipe!.note)
  if (noted.length) {
    p('## Notes the kitchen left')
    p()
    for (const r of noted) p(`- **${esc(r.dish_label)}${r.variation_label ? ` · ${esc(r.variation_label)}` : ''}** — ${esc(r.recipe!.note!)}`)
    p()
  }

  // ── what is missing ────────────────────────────────────────────────────────
  p('## Still to write');
  p()
  if (!todo.length) p('Nothing — every dish the POS has sold has a recipe.')
  else {
    p('Heaviest first. Until a dish is here, it sells and deducts nothing.')
    p()
    p('| Dish | Choices | Sold | Revenue |')
    p('|---|---|---|---|')
    for (const r of todo.slice(0, 120)) {
      p(`| ${esc(r.dish_label)} | ${esc(r.variation_label) || '—'} | ${r.sold} | RM ${r.revenue.toFixed(2)} |`)
    }
    if (todo.length > 120) p(`\n*…and ${todo.length - 120} more.*`)
  }
  p()

  const uncounted = ingredients.filter(i => !i.counted)
  if (uncounted.length) {
    p('## Written down but not counted yet')
    p()
    p('These appear in recipes and in food cost but move no stock, so they cannot')
    p('invent a balance. Turn counting on once there is a way to measure them.')
    p()
    for (const i of uncounted) p(`- ${i.name} (in ${i.unit === 'g' ? 'grams' : i.unit === 'fish' ? 'fish' : 'pieces'})`)
    p()
  }

  return out.join('\n')
}
